INSERT INTO APPLICATION_USERS values (1, 'User1Name', '1234','admin');
INSERT INTO APPLICATION_USERS values (2, 'User2Name', '1234','manager');
INSERT INTO APPLICATION_USERS values (3, 'User3Name', '1234','employee');
INSERT INTO APPLICATION_USERS values (4, 'User4Name', '1234','customer');

INSERT INTO ROLE values (1, 'ADMINISTRATOR');
INSERT INTO ROLE values (2, 'MANAGER');
INSERT INTO ROLE values (3, 'EMPLOYEE');
INSERT INTO ROLE values (4, 'CUSTOMER');

INSERT INTO APPLICATION_USERS_ROLES values (1,1);
INSERT INTO APPLICATION_USERS_ROLES values (2,2);
INSERT INTO APPLICATION_USERS_ROLES values (3,3);
INSERT INTO APPLICATION_USERS_ROLES values (4,4);