CREATE MEMORY TABLE IF NOT EXISTS "APPLICATION_USERS"(
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "USERNAME" VARCHAR(255)
);
CREATE MEMORY TABLE IF NOT EXISTS "APPLICATION_USERS_ROLES"(
    "USER_ID" BIGINT NOT NULL,
    "ROLES_ID" BIGINT NOT NULL
);
CREATE MEMORY TABLE IF NOT EXISTS "ROLE"(
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(255)
);